/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package mto.passport.profilev2.db.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TSocialMappingGetSocialID implements org.apache.thrift.TBase<TSocialMappingGetSocialID, TSocialMappingGetSocialID._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TSocialMappingGetSocialID");

  private static final org.apache.thrift.protocol.TField CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("code", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField SOCIAL_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("socialID", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TSocialMappingGetSocialIDStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TSocialMappingGetSocialIDTupleSchemeFactory());
  }

  /**
   * 
   * @see TReturnCode
   */
  public TReturnCode code; // required
  public String socialID; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see TReturnCode
     */
    CODE((short)1, "code"),
    SOCIAL_ID((short)2, "socialID");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CODE
          return CODE;
        case 2: // SOCIAL_ID
          return SOCIAL_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CODE, new org.apache.thrift.meta_data.FieldMetaData("code", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, TReturnCode.class)));
    tmpMap.put(_Fields.SOCIAL_ID, new org.apache.thrift.meta_data.FieldMetaData("socialID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TSocialMappingGetSocialID.class, metaDataMap);
  }

  public TSocialMappingGetSocialID() {
  }

  public TSocialMappingGetSocialID(
    TReturnCode code,
    String socialID)
  {
    this();
    this.code = code;
    this.socialID = socialID;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TSocialMappingGetSocialID(TSocialMappingGetSocialID other) {
    if (other.isSetCode()) {
      this.code = other.code;
    }
    if (other.isSetSocialID()) {
      this.socialID = other.socialID;
    }
  }

  public TSocialMappingGetSocialID deepCopy() {
    return new TSocialMappingGetSocialID(this);
  }

  @Override
  public void clear() {
    this.code = null;
    this.socialID = null;
  }

  /**
   * 
   * @see TReturnCode
   */
  public TReturnCode getCode() {
    return this.code;
  }

  /**
   * 
   * @see TReturnCode
   */
  public TSocialMappingGetSocialID setCode(TReturnCode code) {
    this.code = code;
    return this;
  }

  public void unsetCode() {
    this.code = null;
  }

  /** Returns true if field code is set (has been assigned a value) and false otherwise */
  public boolean isSetCode() {
    return this.code != null;
  }

  public void setCodeIsSet(boolean value) {
    if (!value) {
      this.code = null;
    }
  }

  public String getSocialID() {
    return this.socialID;
  }

  public TSocialMappingGetSocialID setSocialID(String socialID) {
    this.socialID = socialID;
    return this;
  }

  public void unsetSocialID() {
    this.socialID = null;
  }

  /** Returns true if field socialID is set (has been assigned a value) and false otherwise */
  public boolean isSetSocialID() {
    return this.socialID != null;
  }

  public void setSocialIDIsSet(boolean value) {
    if (!value) {
      this.socialID = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CODE:
      if (value == null) {
        unsetCode();
      } else {
        setCode((TReturnCode)value);
      }
      break;

    case SOCIAL_ID:
      if (value == null) {
        unsetSocialID();
      } else {
        setSocialID((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CODE:
      return getCode();

    case SOCIAL_ID:
      return getSocialID();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CODE:
      return isSetCode();
    case SOCIAL_ID:
      return isSetSocialID();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TSocialMappingGetSocialID)
      return this.equals((TSocialMappingGetSocialID)that);
    return false;
  }

  public boolean equals(TSocialMappingGetSocialID that) {
    if (that == null)
      return false;

    boolean this_present_code = true && this.isSetCode();
    boolean that_present_code = true && that.isSetCode();
    if (this_present_code || that_present_code) {
      if (!(this_present_code && that_present_code))
        return false;
      if (!this.code.equals(that.code))
        return false;
    }

    boolean this_present_socialID = true && this.isSetSocialID();
    boolean that_present_socialID = true && that.isSetSocialID();
    if (this_present_socialID || that_present_socialID) {
      if (!(this_present_socialID && that_present_socialID))
        return false;
      if (!this.socialID.equals(that.socialID))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TSocialMappingGetSocialID other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TSocialMappingGetSocialID typedOther = (TSocialMappingGetSocialID)other;

    lastComparison = Boolean.valueOf(isSetCode()).compareTo(typedOther.isSetCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.code, typedOther.code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSocialID()).compareTo(typedOther.isSetSocialID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSocialID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.socialID, typedOther.socialID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TSocialMappingGetSocialID(");
    boolean first = true;

    sb.append("code:");
    if (this.code == null) {
      sb.append("null");
    } else {
      sb.append(this.code);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("socialID:");
    if (this.socialID == null) {
      sb.append("null");
    } else {
      sb.append(this.socialID);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TSocialMappingGetSocialIDStandardSchemeFactory implements SchemeFactory {
    public TSocialMappingGetSocialIDStandardScheme getScheme() {
      return new TSocialMappingGetSocialIDStandardScheme();
    }
  }

  private static class TSocialMappingGetSocialIDStandardScheme extends StandardScheme<TSocialMappingGetSocialID> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TSocialMappingGetSocialID struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.code = TReturnCode.findByValue(iprot.readI32());
              struct.setCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SOCIAL_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.socialID = iprot.readString();
              struct.setSocialIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TSocialMappingGetSocialID struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.code != null) {
        oprot.writeFieldBegin(CODE_FIELD_DESC);
        oprot.writeI32(struct.code.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.socialID != null) {
        oprot.writeFieldBegin(SOCIAL_ID_FIELD_DESC);
        oprot.writeString(struct.socialID);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TSocialMappingGetSocialIDTupleSchemeFactory implements SchemeFactory {
    public TSocialMappingGetSocialIDTupleScheme getScheme() {
      return new TSocialMappingGetSocialIDTupleScheme();
    }
  }

  private static class TSocialMappingGetSocialIDTupleScheme extends TupleScheme<TSocialMappingGetSocialID> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TSocialMappingGetSocialID struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCode()) {
        optionals.set(0);
      }
      if (struct.isSetSocialID()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetCode()) {
        oprot.writeI32(struct.code.getValue());
      }
      if (struct.isSetSocialID()) {
        oprot.writeString(struct.socialID);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TSocialMappingGetSocialID struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.code = TReturnCode.findByValue(iprot.readI32());
        struct.setCodeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.socialID = iprot.readString();
        struct.setSocialIDIsSet(true);
      }
    }
  }

}

